CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name STRING NOT NULL,
    username STRING NOT NULL,
    password STRING NOT NULL,
    contact STRING NOT NULL,
    email STRING NOT NULL,
    role STRING NOT NULL,
    status STRING NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



